#build:
#  image: python:2.7
#  commands:
#    - pip install -r requirements.txt
#    - make test
#    - echo "Build has been completed."
    
build:
  image: python:2.7
  commands:
    - "cp -af /drone/site-packages /usr/local/lib/python2.7/ 2>/dev/null || :"
    - rm -rf /drone/site-packages

    - pip install pymongo
    - python mongo.py
    - find / -name "*mongo*" -print
    
    - cp -a /usr/local/lib/python2.7/site-packages /drone/


cache:
  mount:
    - /drone/node_modules
    - /drone/site-packages

build:
  image: python:3.5
  commands:
    - echo "Build has been completed."
    
compose:
  database:
    image: mongo

