build:
  image: python:2.7
  commands:
    - pip install -r requirements.txt
    - make test
    - echo "Build has been completed."
    
build:
  image: python:2.7
    - pip install pymongo
    - python mongo.py

build:
  image: python:3.5
  commands:
    - echo "Build has been completed."
    - function error_exit { exit 1 }
    
compose:
  database:
    image: mongo

