language: python
python:
  - "2.7"

# command to install dependencies
install:
  - echo
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

# command to run tests
script:
  - make coverage

after_script:
  - codecov
